version: "2.0"
services:
    app:
        build: .
        # image: rid9/redirex:__TAG__
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.redirex.rule=Host(`r.kryk.io`)"
            - "traefik.http.routers.redirex.entrypoints=web"
            - "traefik.docker.network=global"
        env_file:
            - prod.env
        networks:
            default:
            global:
                aliases:
                    - redirex
        volumes:
            - ./data:/app/data

networks:
    global:
        external: true
